"""add foto to trabalhador

Revision ID: 2a5d8ca36148
Revises: 61038968b965
Create Date: 2026-02-18 21:25:09.418082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a5d8ca36148'
down_revision = '61038968b965'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trabalhador', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trabalhador', schema=None) as batch_op:
        batch_op.drop_column('foto')

    # ### end Alembic commands ###
