"""add cidade and estado to trabalhador

Revision ID: 5e3fffacfd72
Revises: 09ec8fc85d11
Create Date: 2026-02-17 12:46:55.983609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e3fffacfd72'
down_revision = '09ec8fc85d11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trabalhador', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cidade', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('estado', sa.String(length=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trabalhador', schema=None) as batch_op:
        batch_op.drop_column('estado')
        batch_op.drop_column('cidade')

    # ### end Alembic commands ###
