"""add usuario_id to trabalhador

Revision ID: 6509282fcc6a
Revises: 2a5d8ca36148
Create Date: 2026-02-18 22:43:52.932137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6509282fcc6a'
down_revision = '2a5d8ca36148'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('trabalhador', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario_id', sa.Integer(), nullable=True))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trabalhador', schema=None) as batch_op:
        batch_op.drop_column('usuario_id')

    # ### end Alembic commands ###
