from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd7877ac6130'
down_revision = '6509282fcc6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trabalhador', schema=None) as batch_op:
        batch_op.create_foreign_key(
            'fk_trabalhador_usuario_id',
            'usuarios',
            ['usuario_id'],
            ['id']
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trabalhador', schema=None) as batch_op:
        batch_op.drop_constraint('fk_trabalhador_usuario_id', type_='foreignkey')
    # ### end Alembic commands ### 